services:
  postgres:
    image: postgis/postgis:latest  # Use the latest postgis image
    ports:
      - "5432:5432"  # Map container port 5432 to host port 5432
    environment:
      POSTGRES_USER: postgres  # Database username
      POSTGRES_PASSWORD: password  # Database password
      POSTGRES_DB: collisions  # Database name
    volumes:
      # Move the needed scripts into the docker initialization directory to be executed on the first boot.
      - ./databases/init-scripts:/docker-entrypoint-initdb.d
      # Mount a volume to persist data
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
#  basic-server:
#    image: collision-mapper
#    container_name: kotlin-ktor-server
#    ports:
#      - "8888:8888"
#    environment:
#      PORT: 8888
#      APP: /opt/applications/basic-server.jar
#  data-analyzer:
#    image: collision-mapper
#    container_name: kotlin-ktor-analyzer
#    ports:
#      - "8887:8887"
#    environment:
#      PORT: 8887
#      APP: /opt/applications/data-analyzer-server.jar
#      DATABASE_HOST: "host.docker.internal"
#  data-collector:
#    image: collision-mapper
#    container_name: kotlin-ktor-collector
#    ports:
#      - "8886:8886"
#    environment:
#      PORT: 8886
#      APP: /opt/applications/data-collector-server.jar
#      DATABASE_HOST: "host.docker.internal"
#    depends_on:
#      postgres:
#        condition: service_healthy
volumes:
  postgres-data:
