name: deploy-review
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: collision-mapper

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: "build"
        run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: basic-server.jar
          path: applications/basic-server/build/libs/basic-server.jar
          retention-days: 1
      - uses: actions/upload-artifact@v4
        with:
          name: data-analyzer-server.jar
          path: applications/data-analyzer-server/build/libs/data-analyzer-server.jar
          retention-days: 1
      - uses: actions/upload-artifact@v4
        with:
          name: data-collector-server.jar
          path: applications/data-collector-server/build/libs/data-collector-server.jar
          retention-days: 1
  artifact-registry:
    runs-on: ubuntu-latest
    needs: [run-tests]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
      - uses: actions/download-artifact@v4
        with:
          name: basic-server.jar
          path: applications/basic-server/build/libs
      - uses: actions/download-artifact@v4
        with:
          name: data-analyzer-server.jar
          path: applications/data-analyzer-server/build/libs
      - uses: actions/download-artifact@v4
        with:
          name: data-collector-server.jar
          path: applications/data-collector-server/build/libs
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: ${{ secrets.GOOGLE_KEY }}
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag application-container

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u flyingmonkeys1996 --password-stdin
          IMAGE_ID=flyingmonkeys1996/$IMAGE_NAME
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag collision-mapper $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  basic-server-review:
    runs-on: ubuntu-latest
    needs: [artifact-registry]
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: ${{ secrets.GOOGLE_KEY }}
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          echo "gcloud authenticated"

  deploy-data-analyzer-review:
    runs-on: ubuntu-latest
    needs: [artifact-registry]
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: ${{ secrets.GOOGLE_KEY }}
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          echo "gcloud authenticated"

  data-collector-review:
    runs-on: ubuntu-latest
    needs: [artifact-registry]
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: ${{ secrets.GOOGLE_KEY }}
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          echo "gcloud authenticated"
